### ISSUE TITLE
--smart/-S has been removed. Use +smart or -smart extension instead

### ISSUE THREAD

**Issue by davdent** [joostkremers/pandoc-mode#101]
I get this error message: 
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.

Current settings:

((citeproc . t)
 (bibliography "Grand_alliance.json")
 (standalone . t)
 (smart . t)
 (read . "org")
 (write . "docx"))

I am running pandoc mode v. 2.30.1 with Emacs 26.3
Am I doing something wrong or is this  a change in Pandoc that needs to be updated in pandoc mode? 
Thanks for a very useful program!

**Comment by joostkremers** [comment]
Yes, the `--smart` switch is obsolete. But `pandoc-mode` has already been updated to reflect this: the `smart` option should be marked with an asterisk `*` in the `pandoc-mode` menu.

You should remove this option from your options file (simply unsetting in in the menu should be enough), and instead activate the `smart` extension (in the input format menu, there's an option `X: Extensions`).

I usually leave in obsolete switches, so that people who still rely on older Pandoc versions aren't left out. But if you keep your Pandoc installation up-to-date, you shouldn't use any of the options that are marked with an asterisk, as they are obsolete.

**Comment by davdent** [comment]
Thank you for this explanation. This solves my issue.
