### ISSUE TITLE
Pandoc-mode does not recognize utf-8 characters that pandoc recognizes

### ISSUE THREAD

**Issue by renzo-orsini** [joostkremers/pandoc-mode#12]
I have a file with utf-8 characters inside (accented letters). When I try to produce ANY output file (including pdf, html, etc.), I get the following error:

pandoc: Cannot decode byte '\xe8': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

but if I call from the shell the equivalent command, for instance:

pandoc --read=markdown --output=PropostaIndice.pdf PropostaIndice.md

the resulting pdf (or html, or wathever) is produced and contains the accented letters.

**Comment by billbrod** [comment]
I'm having this exact same issue: I have some French accented characters in a markdown file I'm trying to convert to a pdf. When I try to use pandoc-mode I get:

     Running `pandoc --read=markdown --output=c:/Users/wfb6/Desktop/SfN.2015//abstract.pdf --standalone -V geometry:margin=2cm'`
     pandoc.exe: Cannot decode byte '\xe7': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

But if I type the same command into pandoc on the command prompt, it converts it without problem.

I'm using pandoc-mode version 2.12, pandoc 1.13.2, Emacs 24.4.1, on Windows 7.

**Comment by joostkremers** [comment]
Hi, sorry for the late reply. Try the latest update, it'll hopefully fix the issue.

**Comment by billbrod** [comment]
Yup, that fixed it. Thanks!

**Comment by bambax** [comment]
Hello, I have the same error with version 1.15.1 (tested on Ubuntu 64bits and Windows 7) when trying to convert Word documents in French to xml-docbook.

The exact error is `pandoc: Cannot decode byte '\xde': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream`

The command used is: `pandoc -f docbook -o output.xml input.docx`

The error happens when trying to output to xml-docbook, but _not_ when outputting to xhtml... which is weird...? Does this mean it's a write issue (as opposed to a read issue)?

**Comment by nikitaswank** [comment]
Hi, sorry for the inconvenience, I'm having that issue (cannot decode byte '\xe1') when I use --template=filename.tex

**Comment by joostkremers** [comment]
If you have the issue when you use your own template `filename.tex`, then that file is probably not utf-8 encoded. You should reencode the file in utf-8, then it should work. You can do this very easily in Emacs if you open the file, then type `C-x RET f` (`set-buffer-file-coding-system`) and then provide a utf-8 encoding (simply `utf-8` will probably do).

**Comment by Iluneva** [comment]
Hi! I have the same issue for Russian:

Cannot decode byte '\xcf': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream.

**Comment by joostkremers** [comment]
Can you confirm that the relevant file is actually utf-8 encoded? If it isn't, that's obviously the problem. If it is, what version of Emacs and pandoc-mode are you using?

**Comment by boardtc** [comment]
I am getting this error now doing `pandoc (get-item *.md).FullName -o markdown_book.html` on Powershell.  I get pandoc.exe: Cannot decode byte '\x92': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

**Comment by joostkremers** [comment]
@boardtc Are you getting this error when calling Pandoc from the command line or from Emacs? Note that the fact that your files look fine is no guarantee that they are properly utf-8 encoded, especially in Emacs...

**Comment by boardtc** [comment]
Thanks, @joostkremers. I am getting in running from Powershell, the files are created in a windows text editor.

**Comment by joostkremers** [comment]
So if you're not using Emacs to edit the files nor to run pandoc on them, you seem to be posting to the wrong forum. :smiley:

FWIW, the error you get strongly indicates that your files aren't properly utf-8 encoded. `\x92` is reserved as a control code in Unicode, but it is used in CP-1252, the encoding that Windows (used to?) use internally, so I suspect that's where the problem is.

I suggest you ask on Pandoc's mailing list, there might be people there who can help you:

http://pandoc.org/help.html

**Comment by boardtc** [comment]
Sorry I did not know this was an emacs group. Thanks for your patience & help.
