### ISSUE TITLE
Export PDF for chinese text it failed.

### ISSUE THREAD

**Issue by lwx5924** [joostkremers/pandoc-mode#67]
Log as below:

! Package inputenc Error: Unicode char 你 (U+4F60)

(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.

Type  H <return>  for immediate help.

 ...                                              

                                                  

l.63 test 你

Try running pandoc with --latex-engine=xelatex.
pandoc.exe: Error producing PDF

**Comment by joostkremers** [comment]
This is ultimately a LaTeX problem, it's not something `pandoc-mode` can do anything about. Basically, standard LaTeX has a hard time handling Chinese characters.

Perhaps this wiki entry can help you:

https://github.com/jgm/pandoc/wiki/Pandoc-with-Chinese

Otherwise I would suggest asking on the Pandoc mailing list, people there are more likely to be able to help you.
