### ISSUE TITLE
Some Hydras (=pandoc menus) are displayed two times, using up the whole screen

### ISSUE THREAD

**Issue by publicimageltd** [joostkremers/pandoc-mode#68]
I have that weird behaviour that some hydra menus are displayed two times. For example, if I try to set thje options for a specific writer, the list of options is doubled, and I cannot even see the bottom options which are usually separated by a line. That seems to be correlated with the 'color' of the hydra, or the way pandoc creates the menu, since it only affects some menus. The main menu, i.e., is not affected by this bug.

I have the updated versions of emacs, pandoc and hydra.

**Comment by joostkremers** [comment]
Yes, I've seen this happen too, though I've not been able to figure out what's wrong. The problem seems to be related to the fact that `pandoc-mode` creates some of its hydras dynamically. Under certain circumstances the lists on which these dynamic hydras are based are not set up correctly, I think.

In my experience the problem can be solved by deleting the package, restarting Emacs and reinstalling. It's important that you quit and restart Emacs before reinstalling, to get rid of any lingering function and variable definitions.

**Comment by publicimageltd** [comment]
Deleting the package, quitting emacs, reinstalling it -- worked. Thanks for this workaround!
