### ISSUE TITLE
Beamer should output to pdf

### ISSUE THREAD

**Issue by newhallroad** [joostkremers/pandoc-mode#80]
Converting from md to beamer outputs a `.tex` file. Performing the same conversion on the cli outputs a `.pdf` which seems more intuitive as I would expect a pdf slides as the output. Is there a setting I am missing that would give me pdf slides?
Many thanks

**Comment by joostkremers** [comment]
As it turns out, this is an omission in `pandoc-mode`. In order to create a pdf with `pandoc-mode`, you need to call `C-c / p` instead of `C-c / r`. Since creating a pdf can only be done with a few output formats, `pandoc-mode` makes sure you're using one of these. However, I neglected to make sure that `beamer` is on the list of possible output formats.

This should be fixed now in the latest commit.

Thanks for reporting this!

**Comment by newhallroad** [comment]
That makes total sense. Thanks, as always, for being so responsive.
